import { captionExcerpt } from './social-model.mjs';
// Reused from Clara's Login Kit + Display API connector.
export const TIKTOK_SCOPES=['user.info.basic','user.info.stats','video.list'];
const API='https://open.tiktokapis.com/v2';
export class TikTokError extends Error{constructor(reconnect=false){super(reconnect?'Reconnect TikTok to continue.':'TikTok could not answer this request.');this.needsReconnect=reconnect;}}
export function tiktokConfig(env=process.env){const clientKey=env.TIKTOK_CLIENT_KEY?.trim(),clientSecret=env.TIKTOK_CLIENT_SECRET?.trim();const missing=['TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET'].filter(name=>!env[name]?.trim());return{clientKey,clientSecret,missing,canSync:!missing.length,canConnect:!missing.length&&Boolean(env.SOCIAL_OAUTH_STATE_SECRET?.length>=32),connectMissing:[...missing,...(env.SOCIAL_OAUTH_STATE_SECRET?.length>=32?[]:['SOCIAL_OAUTH_STATE_SECRET'])]};}
export function tiktokAuthorizeUrl({clientKey,redirect,state}){const url=new URL('https://www.tiktok.com/v2/auth/authorize/');for(const [name,value]of Object.entries({client_key:clientKey,redirect_uri:redirect,scope:TIKTOK_SCOPES.join(','),response_type:'code',state}))url.searchParams.set(name,value);return url.toString();}
async function tokenRequest(config,values,fetchImpl){const body=new URLSearchParams({client_key:config.clientKey,client_secret:config.clientSecret,...values});const response=await fetchImpl(API+'/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body,cache:'no-store',signal:AbortSignal.timeout(25000)});const data=await response.json().catch(()=>null);if(!response.ok||!data?.access_token||!data?.refresh_token)throw new TikTokError(['invalid_grant','invalid_token'].includes(data?.error));const now=Date.now();return{bundle:{accessToken:data.access_token,refreshToken:data.refresh_token,openId:data.open_id,expiresAt:now+Number(data.expires_in)*1000,refreshExpiresAt:now+Number(data.refresh_expires_in)*1000},scopes:String(data.scope??'').split(',').filter(Boolean)};}
function safeFetch(fetchImpl) {
  return async (...args) => { try { return await fetchImpl(...args); } catch { throw new TikTokError(); } };
}
export function exchangeTikTokCode({code,redirect,env=process.env,fetchImpl=fetch}){const config=tiktokConfig(env);if(!config.canSync)throw new TikTokError();return tokenRequest(config,{grant_type:'authorization_code',code,redirect_uri:redirect},safeFetch(fetchImpl));}
export function createTikTokClient({bundle,env=process.env,fetchImpl=fetch,persist=async()=>{}}){
 fetchImpl=safeFetch(fetchImpl);
 const config=tiktokConfig(env);if(!config.canSync)throw new TikTokError();
 async function accessToken(){if(bundle.expiresAt<Date.now()+60000){const renewed=await tokenRequest(config,{grant_type:'refresh_token',refresh_token:bundle.refreshToken},fetchImpl);await persist(renewed.bundle);bundle=renewed.bundle;}return bundle.accessToken;}
 async function request(route,fields,body){const url=new URL(API+route);url.searchParams.set('fields',fields);const response=await fetchImpl(url,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+await accessToken(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',signal:AbortSignal.timeout(25000)});const data=await response.json().catch(()=>null);if(!response.ok||data?.error?.code!=='ok')throw new TikTokError(response.status===401||data?.error?.code==='access_token_invalid');return data.data;}
 return {async profile(){return(await request('/user/info/','open_id,display_name,avatar_url,follower_count,likes_count,video_count')).user;},videos(cursor){return request('/video/list/','id,create_time,title,video_description,cover_image_url,share_url,like_count,comment_count,share_count,view_count',{max_count:20,...(cursor?{cursor:Number(cursor)}:{})});}};
}
export function foldTikTokVideo(video){const number=value=>value===null||value===undefined||!Number.isFinite(Number(value))?null:Number(value);const likes=number(video.like_count),comments=number(video.comment_count),shares=number(video.share_count);return{external_id:String(video.id),published_at:new Date(Number(video.create_time)*1000).toISOString(),media_type:'video',caption_excerpt:captionExcerpt(video.video_description??video.title),permalink:video.share_url??null,thumbnail_url:video.cover_image_url??null,views:number(video.view_count),likes,comments,shares,engagement:[likes,comments,shares].every(v=>v!==null)?likes+comments+shares:null,reach:null,saves:null,follows:null};}
